name: publish library when have a push action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-libraries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        id: setup-java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'

      - name: Setup Gradle
        id: setup-gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        id: grant-gradle-permission
        run: chmod +x ./gradlew

      - name: Setup changed files
        id: setup-changed-files
        uses: tj-actions/changed-files@v44
      # NOTE: `since_last_remote_commit: true` is implied by default and falls back to the previous local commit.

      - name: Build and publish libraries to nexus
        env:
          ALL_CHANGED_FILES: ${{ steps.setup-changed-files.outputs.all_changed_files }}
        run: |
          declare -A changed_folders
          
          for file in ${ALL_CHANGED_FILES}; do
            echo "folder ${file%%/*} was changed"
            if [[ ${file%%/*} != *".github"* ]]; then
              changed_folders[${file%%/*}]=${file%%/*}
            fi
          done
          
          for folder in "${!changed_folders[@]}"; do
            echo "process deploy $folder library"
            cd ${folder}
            echo "moved to ${PWD}"
            ../gradlew clean build publishToNexusRepo
            echo "published $folder library to nexus"
            cd .. 
          done