name: Publish Library on Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-libraries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Detect changed files
        id: changed-files
        uses: tj-actions/changed-files@v46

      - name: Build and publish changed modules
        run: |
          declare -A changed_modules

          # Duyệt qua danh sách file thay đổi
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            module=${file%%/*}  # Lấy thư mục gốc của file

            echo "Detected change in: $module"

            # Chỉ thêm vào nếu nó là module hợp lệ (chứa build.gradle hoặc build.gradle.kts)
            if [[ -d $module && (-f "$module/build.gradle" || -f "$module/build.gradle.kts") ]]; then
              changed_modules[$module]=$module
            fi
          done

          # Kiểm tra nếu không có module nào thay đổi thì thoát
          if [[ ${#changed_modules[@]} -eq 0 ]]; then
            echo "No modules changed, skipping deployment."
            exit 0
          fi

          # Build và publish từng module từ thư mục root
          for module in "${!changed_modules[@]}"; do
            echo "📦 Deploying module: $module"

            # Chạy Gradle từ thư mục root, chỉ định module với -p
            ./gradlew -p $module clean build publishToNexusRepo || { echo "❌ Error: Gradle build failed for $module"; exit 1; }

            echo "✅ Published $module to Nexus"
          done
